# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesearch.ui'
#
# Created: Sun Jan 13 00:04:06 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.setEnabled(True)
        main.resize(800, 520)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(720, 480))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(main)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tree = QtGui.QTreeView(self.centralWidget)
        self.tree.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(9)
        self.tree.setFont(font)
        self.tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tree.setAcceptDrops(False)
        self.tree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tree.setDragEnabled(True)
        self.tree.setDragDropOverwriteMode(False)
        self.tree.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tree.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tree.setIndentation(10)
        self.tree.setExpandsOnDoubleClick(False)
        self.tree.setObjectName(_fromUtf8("tree"))
        self.horizontalLayout_3.addWidget(self.tree)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.stop = QtGui.QPushButton(self.centralWidget)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.horizontalLayout.addWidget(self.stop)
        self.searchedit = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchedit.sizePolicy().hasHeightForWidth())
        self.searchedit.setSizePolicy(sizePolicy)
        self.searchedit.setMinimumSize(QtCore.QSize(0, 24))
        self.searchedit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft New Tai Lue"))
        self.searchedit.setFont(font)
        self.searchedit.setAcceptDrops(False)
        self.searchedit.setAutoFillBackground(True)
        self.searchedit.setText(_fromUtf8(""))
        self.searchedit.setObjectName(_fromUtf8("searchedit"))
        self.horizontalLayout.addWidget(self.searchedit)
        self.classlist = QtGui.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(9)
        self.classlist.setFont(font)
        self.classlist.setObjectName(_fromUtf8("classlist"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/doc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon2, _fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/music.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/picture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon4, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon5, _fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon6, _fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/andoc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classlist.addItem(icon7, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.classlist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fileinfo = QtGui.QTableView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileinfo.sizePolicy().hasHeightForWidth())
        self.fileinfo.setSizePolicy(sizePolicy)
        self.fileinfo.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(9)
        self.fileinfo.setFont(font)
        self.fileinfo.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.fileinfo.setAcceptDrops(False)
        self.fileinfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileinfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileinfo.setAutoScroll(False)
        self.fileinfo.setAutoScrollMargin(10)
        self.fileinfo.setDragEnabled(True)
        self.fileinfo.setDragDropOverwriteMode(False)
        self.fileinfo.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.fileinfo.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.fileinfo.setAlternatingRowColors(True)
        self.fileinfo.setShowGrid(False)
        self.fileinfo.setGridStyle(QtCore.Qt.NoPen)
        self.fileinfo.setSortingEnabled(True)
        self.fileinfo.setObjectName(_fromUtf8("fileinfo"))
        self.fileinfo.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.fileinfo)
        self.stretch = QtGui.QToolButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stretch.sizePolicy().hasHeightForWidth())
        self.stretch.setSizePolicy(sizePolicy)
        self.stretch.setMinimumSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.stretch.setFont(font)
        self.stretch.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.stretch.setObjectName(_fromUtf8("stretch"))
        self.horizontalLayout_2.addWidget(self.stretch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.textdetail = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textdetail.sizePolicy().hasHeightForWidth())
        self.textdetail.setSizePolicy(sizePolicy)
        self.textdetail.setMinimumSize(QtCore.QSize(0, 0))
        self.textdetail.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei"))
        font.setPointSize(9)
        self.textdetail.setFont(font)
        self.textdetail.setAutoFillBackground(True)
        self.textdetail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textdetail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textdetail.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textdetail.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textdetail.setObjectName(_fromUtf8("textdetail"))
        self.horizontalLayout_3.addWidget(self.textdetail)
        self.collapse = QtGui.QToolButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collapse.sizePolicy().hasHeightForWidth())
        self.collapse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.collapse.setFont(font)
        self.collapse.setObjectName(_fromUtf8("collapse"))
        self.horizontalLayout_3.addWidget(self.collapse)
        main.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_4 = QtGui.QMenu(self.menuBar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menuSetting = QtGui.QMenu(self.menuBar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuLanguage = QtGui.QMenu(self.menuSetting)
        self.menuLanguage.setObjectName(_fromUtf8("menuLanguage"))
        self.menuAssign_directory = QtGui.QMenu(self.menuSetting)
        self.menuAssign_directory.setObjectName(_fromUtf8("menuAssign_directory"))
        main.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(main)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        main.setStatusBar(self.statusBar)
        self.m_new_index = QtGui.QAction(main)
        self.m_new_index.setWhatsThis(_fromUtf8(""))
        self.m_new_index.setObjectName(_fromUtf8("m_new_index"))
        self.m_update = QtGui.QAction(main)
        self.m_update.setObjectName(_fromUtf8("m_update"))
        self.m_cut = QtGui.QAction(main)
        self.m_cut.setCheckable(True)
        self.m_cut.setObjectName(_fromUtf8("m_cut"))
        self.m_copy = QtGui.QAction(main)
        self.m_copy.setObjectName(_fromUtf8("m_copy"))
        self.m_paste = QtGui.QAction(main)
        self.m_paste.setCheckable(True)
        self.m_paste.setObjectName(_fromUtf8("m_paste"))
        self.m_all = QtGui.QAction(main)
        self.m_all.setObjectName(_fromUtf8("m_all"))
        self.m_set = QtGui.QAction(main)
        self.m_set.setObjectName(_fromUtf8("m_set"))
        self.m_help = QtGui.QAction(main)
        self.m_help.setObjectName(_fromUtf8("m_help"))
        self.m_about = QtGui.QAction(main)
        self.m_about.setObjectName(_fromUtf8("m_about"))
        self.m_matchall = QtGui.QAction(main)
        self.m_matchall.setCheckable(True)
        self.m_matchall.setEnabled(True)
        self.m_matchall.setObjectName(_fromUtf8("m_matchall"))
        self.m_wildcard = QtGui.QAction(main)
        self.m_wildcard.setCheckable(True)
        self.m_wildcard.setEnabled(True)
        self.m_wildcard.setObjectName(_fromUtf8("m_wildcard"))
        self.m_case_sensitive = QtGui.QAction(main)
        self.m_case_sensitive.setCheckable(True)
        self.m_case_sensitive.setObjectName(_fromUtf8("m_case_sensitive"))
        self.m_export = QtGui.QAction(main)
        self.m_export.setObjectName(_fromUtf8("m_export"))
        self.m_exit = QtGui.QAction(main)
        self.m_exit.setObjectName(_fromUtf8("m_exit"))
        self.m_regex = QtGui.QAction(main)
        self.m_regex.setCheckable(True)
        self.m_regex.setObjectName(_fromUtf8("m_regex"))
        self.m_English = QtGui.QAction(main)
        self.m_English.setCheckable(True)
        self.m_English.setObjectName(_fromUtf8("m_English"))
        self.m_Chinese = QtGui.QAction(main)
        self.m_Chinese.setCheckable(True)
        self.m_Chinese.setObjectName(_fromUtf8("m_Chinese"))
        self.m_normal_mode = QtGui.QAction(main)
        self.m_normal_mode.setCheckable(True)
        self.m_normal_mode.setChecked(True)
        self.m_normal_mode.setObjectName(_fromUtf8("m_normal_mode"))
        self.actionContact_us = QtGui.QAction(main)
        self.actionContact_us.setObjectName(_fromUtf8("actionContact_us"))
        self.m_all_volume = QtGui.QAction(main)
        self.m_all_volume.setCheckable(True)
        self.m_all_volume.setChecked(True)
        self.m_all_volume.setObjectName(_fromUtf8("m_all_volume"))
        self.m_select_directory = QtGui.QAction(main)
        self.m_select_directory.setCheckable(True)
        self.m_select_directory.setObjectName(_fromUtf8("m_select_directory"))
        self.m_style = QtGui.QAction(main)
        self.m_style.setObjectName(_fromUtf8("m_style"))
        self.menu.addSeparator()
        self.menu.addAction(self.m_new_index)
        self.menu.addAction(self.m_update)
        self.menu.addSeparator()
        self.menu.addAction(self.m_exit)
        self.menu_3.addAction(self.m_cut)
        self.menu_3.addAction(self.m_copy)
        self.menu_3.addAction(self.m_paste)
        self.menu_3.addAction(self.m_all)
        self.menu_2.addAction(self.m_normal_mode)
        self.menu_2.addAction(self.m_matchall)
        self.menu_2.addAction(self.m_wildcard)
        self.menu_2.addAction(self.m_regex)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.m_case_sensitive)
        self.menu_4.addAction(self.m_help)
        self.menu_4.addAction(self.m_about)
        self.menuLanguage.addAction(self.m_English)
        self.menuLanguage.addAction(self.m_Chinese)
        self.menuAssign_directory.addAction(self.m_all_volume)
        self.menuAssign_directory.addAction(self.m_select_directory)
        self.menuSetting.addAction(self.menuLanguage.menuAction())
        self.menuSetting.addAction(self.menuAssign_directory.menuAction())
        self.menuSetting.addAction(self.m_style)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(QtGui.QApplication.translate("main", "FileSearcher", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.setStatusTip(QtGui.QApplication.translate("main", "the file system tree", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("main", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(0, QtGui.QApplication.translate("main", "All Files", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(1, QtGui.QApplication.translate("main", "Document", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(2, QtGui.QApplication.translate("main", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(3, QtGui.QApplication.translate("main", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(4, QtGui.QApplication.translate("main", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(5, QtGui.QApplication.translate("main", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.classlist.setItemText(6, QtGui.QApplication.translate("main", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.stretch.setText(QtGui.QApplication.translate("main", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.textdetail.setStatusTip(QtGui.QApplication.translate("main", "give a stretch of the file", None, QtGui.QApplication.UnicodeUTF8))
        self.collapse.setText(QtGui.QApplication.translate("main", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("main", "edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("main", "option", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("main", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSetting.setTitle(QtGui.QApplication.translate("main", "setting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLanguage.setTitle(QtGui.QApplication.translate("main", "language", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAssign_directory.setTitle(QtGui.QApplication.translate("main", "assign directory", None, QtGui.QApplication.UnicodeUTF8))
        self.m_new_index.setText(QtGui.QApplication.translate("main", "new index", None, QtGui.QApplication.UnicodeUTF8))
        self.m_new_index.setStatusTip(QtGui.QApplication.translate("main", "create a new index", None, QtGui.QApplication.UnicodeUTF8))
        self.m_new_index.setShortcut(QtGui.QApplication.translate("main", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.m_update.setText(QtGui.QApplication.translate("main", "update index", None, QtGui.QApplication.UnicodeUTF8))
        self.m_update.setStatusTip(QtGui.QApplication.translate("main", "update the index,if you have a index already,it is much faster", None, QtGui.QApplication.UnicodeUTF8))
        self.m_update.setShortcut(QtGui.QApplication.translate("main", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.m_cut.setText(QtGui.QApplication.translate("main", "cut", None, QtGui.QApplication.UnicodeUTF8))
        self.m_cut.setStatusTip(QtGui.QApplication.translate("main", "cut", None, QtGui.QApplication.UnicodeUTF8))
        self.m_cut.setShortcut(QtGui.QApplication.translate("main", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.m_copy.setText(QtGui.QApplication.translate("main", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.m_copy.setStatusTip(QtGui.QApplication.translate("main", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.m_copy.setShortcut(QtGui.QApplication.translate("main", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.m_paste.setText(QtGui.QApplication.translate("main", "paste", None, QtGui.QApplication.UnicodeUTF8))
        self.m_paste.setStatusTip(QtGui.QApplication.translate("main", "paste", None, QtGui.QApplication.UnicodeUTF8))
        self.m_paste.setShortcut(QtGui.QApplication.translate("main", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.m_all.setText(QtGui.QApplication.translate("main", "select all", None, QtGui.QApplication.UnicodeUTF8))
        self.m_all.setStatusTip(QtGui.QApplication.translate("main", "select all", None, QtGui.QApplication.UnicodeUTF8))
        self.m_all.setShortcut(QtGui.QApplication.translate("main", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.m_set.setText(QtGui.QApplication.translate("main", "setting", None, QtGui.QApplication.UnicodeUTF8))
        self.m_help.setText(QtGui.QApplication.translate("main", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.m_help.setShortcut(QtGui.QApplication.translate("main", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.m_about.setText(QtGui.QApplication.translate("main", "about...", None, QtGui.QApplication.UnicodeUTF8))
        self.m_matchall.setText(QtGui.QApplication.translate("main", "match whole word", None, QtGui.QApplication.UnicodeUTF8))
        self.m_matchall.setStatusTip(QtGui.QApplication.translate("main", "just match the whole word", None, QtGui.QApplication.UnicodeUTF8))
        self.m_wildcard.setText(QtGui.QApplication.translate("main", "use wildcard", None, QtGui.QApplication.UnicodeUTF8))
        self.m_wildcard.setStatusTip(QtGui.QApplication.translate("main", "match directory when search,is is closed by default", None, QtGui.QApplication.UnicodeUTF8))
        self.m_case_sensitive.setText(QtGui.QApplication.translate("main", "case sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.m_case_sensitive.setStatusTip(QtGui.QApplication.translate("main", "dont\'t ignore the case of the word,it is closed by default", None, QtGui.QApplication.UnicodeUTF8))
        self.m_export.setText(QtGui.QApplication.translate("main", "export...", None, QtGui.QApplication.UnicodeUTF8))
        self.m_exit.setText(QtGui.QApplication.translate("main", "exit...", None, QtGui.QApplication.UnicodeUTF8))
        self.m_exit.setStatusTip(QtGui.QApplication.translate("main", "exit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.m_exit.setShortcut(QtGui.QApplication.translate("main", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.m_regex.setText(QtGui.QApplication.translate("main", "regex expression", None, QtGui.QApplication.UnicodeUTF8))
        self.m_regex.setStatusTip(QtGui.QApplication.translate("main", "use the regular expression to search,it is closed by default", None, QtGui.QApplication.UnicodeUTF8))
        self.m_English.setText(QtGui.QApplication.translate("main", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.m_Chinese.setText(QtGui.QApplication.translate("main", "中文-简体", None, QtGui.QApplication.UnicodeUTF8))
        self.m_normal_mode.setText(QtGui.QApplication.translate("main", "normal mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContact_us.setText(QtGui.QApplication.translate("main", "Contact us", None, QtGui.QApplication.UnicodeUTF8))
        self.m_all_volume.setText(QtGui.QApplication.translate("main", "All Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.m_select_directory.setText(QtGui.QApplication.translate("main", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.m_style.setText(QtGui.QApplication.translate("main", "style", None, QtGui.QApplication.UnicodeUTF8))
        self.m_style.setToolTip(QtGui.QApplication.translate("main", "choose style", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    main = QtGui.QMainWindow()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())

